postgresql:
  enabled: false
  fullnameOverride: nango-postgresql
  primary:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1000m"
        memory: "2048Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
  auth:
    postgresPassword: nango
    database: nango

temporal:
  enabled: false
  global:
    serviceAccountName: default
    secretName: nango-secret

server:
  name: nango-server
  replicas: 1

jobs:
  name: nango-jobs
  replicas: 1
  volume:
    aws: true

runner:
  name: nango-runner
  replicas: 1

persist:
  name: persist
  url: http://nango-persist
  replicas: 1
  tag: e6fd036d8bf2f5b7f9a8cd574746821e72b3801e # 2024/06/07

shared:
  namespace: default
  encryptionEnabled: false
  ENV: production
  DB_HOST: nango-postgresql
  DB_USER: postgres
  DB_PORT: "5432"
  DB_NAME: nango
  DB_SSL: false
  CALLBACK_URL: ""

temporalio:
  TEMPORAL_ADDRESS: nango-sync.abc
  TEMPORAL_NAMESPACE: nango-sync.def
