postgresql:
  enabled: false
  fullnameOverride: nango-postgresql
  primary:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1000m"
        memory: "2048Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
  auth:
    postgresPassword: nango
    database: nango

elasticsearch:
  enabled: true
  fullnameOverride: nango-elasticsearch
  clusterName: elastic
  nodeGroup: master
  masterOnly: true
  replicas: 1
  minimumMasterNodes: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "2048Mi"
    requests:
      cpu: "250m"
      memory: "1024Mi"
  security:
    enabled: true
    elasticPassword: "nango"
  service:
    type: ClusterIP
    ports:
      restAPI: 9200
      transport: 9300
  persistence:
    enabled: false
  podSecurityContext:
    fsGroup: 1001
  containerSecurityContext:
    runAsUser: 1001
    runAsNonRoot: true
  readinessProbe:
    initialDelaySeconds: 90
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 20

server:
  name: nango-server
  replicas: 1
  # you can set /any/ nango-server environment variable required utilizing the "env" key as follows:
  # the example below shows a configuration to enable basic auth
  # env:
  #   - name: FLAG_AUTH_ENABLED
  #     value: "false"
  #   - name: NANGO_DASHBOARD_USERNAME
  #     value: nango
  #   - name: NANGO_DASHBOARD_PASSWORD
  #     valueFrom:
  #       secretKeyRef:
  #         name: nango-secrets
  #         key: nango-dashboard-password

jobs:
  name: nango-jobs
  replicas: 1
  clusterAdmin: false
  volume:
    aws: true

runner:
  name: nango-runner
  replicas: 1

persist:
  name: persist
  url: http://nango-persist
  replicas: 1

orchestrator:
  name: orchestrator
  url: http://nango-orchestrator
  replicas: 1

shared:
  namespace: default
  encryptionEnabled: false
  NODE_ENV: production
  NANGO_DB_HOST: nango-postgresql
  NANGO_DB_USER: postgres
  NANGO_DB_PORT: "5432"
  NANGO_DB_NAME: nango
  NANGO_DB_SSL: false
  NANGO_CALLBACK_URL: ""
  NANGO_LOGS_ENABLED: true
  NANGO_LOGS_ES_PWD: nango
  NANGO_LOGS_ES_URL: https://nango-elasticsearch.default.svc.cluster.local:9200
  NANGO_LOGS_ES_USER: elastic
  # 25/01/17 - https://github.com/NangoHQ/nango/commit/f238cf966ffada56dec531d186deff3ac4c8d74b
  tag: f238cf966ffada56dec531d186deff3ac4c8d74b
