apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.jobs.name | default "nango-jobs" }}
spec:
  replicas: {{ .Values.jobs.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.jobs.name | default "nango-jobs" }} 
  template:
    metadata:
      labels:
        app: {{ .Values.jobs.name | default "nango-jobs" }}
    spec:
      containers:
        - name: {{ .Values.jobs.name | default "nango-jobs" }}
          image: nangohq/nango-jobs:production
          imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
          env:
            - name: NANGO_DB_HOST
              value: {{ .Values.shared.DB_HOST }}
            - name: NANGO_DB_NAME
              value: {{ .Values.shared.DB_NAME }}
            - name: NANGO_DB_USER
              value: {{ .Values.shared.DB_USER }}
            - name: NANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nango-postgresql
                  key: postgres-password
            - name: NANGO_DB_PORT
              value: "{{ .Values.shared.DB_PORT | default 5432 }}"
            - name: NANGO_DB_SSL
              value: "{{ .Values.shared.DB_SSL | default false }}"
            - name: NANGO_ENCRYPTION_KEY
              value: {{ .Values.shared.ENCRYPTION_KEY | default "" }}
            - name: NANGO_CALLBACK_URL
              value: {{ .Values.shared.CALLBACK_URL }}
            - name: TEMPORAL_ADDRESS
              value: {{ .Values.temporal.TEMPORAL_ADDRESS }}
            - name: TEMPORAL_NAMESPACE
              value: {{ .Values.temporal.TEMPORAL_NAMESPACE }}
            - name: NODE_ENV
              value: {{ .Values.ENV | default "production" }}
            - name: NANGO_ENTERPRISE
              value: "true"
            - name: NANGO_INTEGRATIONS_FULL_PATH
              value: /flows
          volumeMounts:
            - mountPath: /flows
              name: {{ .Values.jobs.volume.name }}
      volumes:
        - name: {{ .Values.jobs.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.jobs.volume.claimName }}
