{{- if and .Values.shared.useVolumeForFlows .Values.jobs.volume.aws }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.jobs.volume.claimName }}
  namespace: {{ .Values.shared.namespace }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  iopsPerGB: "10"
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
{{- end }}
