apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.temporalio.volumeName }}
type: Opaque
data:
  {{ .Values.temporalio.TEMPORAL_NAMESPACE }}.key: {{ .Values.temporalio.TEMPORAL_KEY }}
  {{ .Values.temporalio.TEMPORAL_NAMESPACE }}.crt: {{ .Values.temporalio.TEMPORAL_CRT }}
