apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.jobs.name | default "nango-jobs" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3005
  selector:
    app: {{ .Values.jobs.name | default "nango-jobs" }}

