{{- if .Values.jobs.clusterAdmin }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobs.name | default "nango-jobs" }}-sa
  namespace: {{ .Values.shared.namespace }}
  labels:
    app: {{ .Values.jobs.name | default "nango-jobs" }}
{{- end }} 