apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jobs.volume.claimName }}
  namespace: {{ .Values.shared.namespace }}
spec:
  storageClassName: {{ .Values.jobs.volume.class }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
