apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.server.name | default "nango-server" }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  selector:
    app: {{ .Values.server.name | default "nango-server" }}
