apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.server.name | default "nango-server" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3003
    - name: https
      port: 443
      targetPort: 3003
  selector:
    app: {{ .Values.server.name | default "nango-server" }}
