apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.server.name | default "nango-server" }}
spec:
  replicas: {{ .Values.server.replicas | default 1 }}
  selector: 
    matchLabels:
      app: {{ .Values.server.name | default "nango-server" }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.name | default "nango-server" }}
    spec:
      containers:
        - name: {{ .Values.server.name | default "nango-server" }}
          image: nangohq/nango:prod-{{ .Values.server.tag | default .Values.shared.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy  | default "Always" }}
          args: ["node", "packages/server/dist/server.js"]
          ports:
            - containerPort: 3003
          env:
            - name: NANGO_DB_HOST
              value: {{ .Values.shared.DB_HOST }}
            - name: NANGO_DB_NAME
              value: {{ .Values.shared.DB_NAME }}
            - name: NANGO_DB_USER
              value: {{ .Values.shared.DB_USER }}
              {{- if .Values.shared.DB_URL }}
              name: NANGO_DATABASE_URL
              value: {{ .Values.shared.DB_URL }}
              {{- end }}
            - name: NANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.postgresql.enabled }}nango-postgresql{{ else }}nango-secrets{{ end }}
                  key: postgres-password
            - name: NANGO_DB_PORT
              value: "{{ .Values.shared.DB_PORT | default 5432 }}"
            - name: NANGO_DB_SSL
              value: "{{ .Values.shared.DB_SSL | default false }}"
              {{- if .Values.shared.encryptionEnabled }}
            - name: NANGO_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: nango-secrets
                  key: encryption-key
              {{- end }}
            - name: NANGO_SERVER_URL
              value: {{ .Values.shared.APP_URL }}
            - name: NANGO_CALLBACK_URL
              value: {{ .Values.shared.CALLBACK_URL }}
            - name: NODE_ENV
              value: {{ .Values.shared.ENV | default "production" }}
            - name: NANGO_ENTERPRISE
              value: "true"
            - name: NANGO_INTEGRATIONS_FULL_PATH
              value: {{ .Values.shared.flows_path }}
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nango-secrets
                  key: mailgun-api-key
            {{- if .Values.server.env }}
            {{- toYaml .Values.server.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.shared.useVolumeForFlows }}
            - mountPath: {{ .Values.shared.flows_path }}
              name: {{ .Values.jobs.volume.name }}
            {{- end }}
      volumes:
        {{- if .Values.shared.useVolumeForFlows }}
        - name: {{ .Values.jobs.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.jobs.volume.claimName }}
        {{- end }}
