apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.server.namespace | .Values.global.namespace }}
  name: {{ include "server.names.component" . }}
spec:
  type: {{ if .Values.server.useLoadBalancer }}LoadBalancer{{ else }}NodePort{{ end }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.server.SERVER_PORT }}
    - name: https
      port: 443
      targetPort: {{ .Values.server.SERVER_PORT }}
  selector:
    app: {{ .Values.server.name | default "nango-server" }}
