server:
  name: server
  replicas: 1

jobs:
  name: jobs
  replicas: 1
  volume:
    class: standard
    name: flows-volume
    claimName: flow-claim
    provisioner: rancher.io/local-path

runner:
  name: runner
  replicas: 1

shared:
  namespace: default
  ENV: production
  DB_HOST: nango-postgresql
  DB_USER: postgres
  DB_PORT: "5432"
  DB_NAME: nango
  DB_SSL: false
  ENCRYPTION_KEY: ""
  CALLBACK_URL: ""

temporalio:
  volumeName: temporal-secrets
  TEMPORAL_ADDRESS: nango-sync.abc
  TEMPORAL_NAMESPACE: nango-sync.def
  TEMPORAL_KEY: BASE_64_VALUE
  TEMPORAL_CRT: BASE_64_VALUE

