postgresql:
  enabled: true
  fullnameOverride: nango-postgresql
  primary:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1000m"
        memory: "2048Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
  auth:
    postgresPassword: nango
    database: nango

temporal:
  enabled: true
  global:
    serviceAccountName: default
    secretName: nango-secret

server:
  name: server
  replicas: 1

jobs:
  name: jobs
  replicas: 1
  volume:
    name: flows-volume
    claimName: flow-claim
    aws: false
    gcp: false

runner:
  name: runner
  replicas: 1

shared:
  namespace: default
  ENV: production
  DB_HOST: nango-postgresql
  DB_USER: postgres
  DB_PORT: "5432"
  DB_NAME: nango
  DB_SSL: false
  ENCRYPTION_KEY: ""
  CALLBACK_URL: ""
  flows_path: /flows
  useVolumeForFlows: true

temporalio:
  volumeName: temporal-secrets
  TEMPORAL_ADDRESS: nango-sync.abc
  TEMPORAL_NAMESPACE: nango-sync.def
  TEMPORAL_KEY: BASE_64_VALUE
  TEMPORAL_CRT: BASE_64_VALUE

