postgresql:
  enabled: true
  fullnameOverride: nango-postgresql
  primary:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1000m"
        memory: "2048Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
  auth:
    postgresPassword: nango
    database: nango

elasticsearch:
  enabled: true
  fullnameOverride: nango-elasticsearch
  clusterName: elastic
  # single node cluster
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  security:
    enabled: true
    elasticPassword: nango

server:
  name: nango-self-server
  url: http://nango-self-server
  replicas: 1
  useLoadBalancer: true
  MAILGUN_API_KEY: ""
  SERVER_PORT: "8080"

jobs:
  name: nango-self-jobs
  url: http://nango-self-jobs
  replicas: 1
  clusterAdmin: false
  volume:
    name: flows-volume
    claimName: flow-claim
    storageClassName: standard
    aws: false
    gcp: false

runner:
  name: nango-self-runner
  url: http://nango-self-runner
  replicas: 1
  nodeId: "1"

persist:
  name: nango-self-persist
  url: http://nango-self-persist
  replicas: 1

orchestrator:
  name: nango-self-orchestrator
  url: http://nango-self-orchestrator
  replicas: 1

shared:
  namespace: default
  encryptionEnabled: false
  flows_path: /flows
  useVolumeForFlows: true
  NODE_ENV: production
  NANGO_DB_HOST: nango-postgresql
  NANGO_DB_USER: postgres
  NANGO_DB_PORT: "5432"
  NANGO_DB_NAME: nango
  NANGO_DB_SSL: false
  NANGO_SERVER_URL: https://your-hosted-instance.com
  NANGO_PUBLIC_CONNECT_URL: https://your-hosted-instance.com
  NANGO_CALLBACK_URL: https://your-hosted-instance.com/oauth/callback
  NANGO_LOGS_ENABLED: true
  NANGO_LOGS_ES_PWD: nango
  NANGO_LOGS_ES_URL: https://nango-elasticsearch.default.svc.cluster.local:9200
  NANGO_LOGS_ES_USER: elastic
  FLAG_SERVE_CONNECT_UI: true
  tag: 6adbaf17e6cba479564277b1f5224f42558454f4 # 2025/02/10
