postgresql:
  enabled: true
  fullnameOverride: nango-postgresql
  primary:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1000m"
        memory: "2048Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
  auth:
    postgresPassword: nango
    database: nango

temporal:
  enabled: false
  global:
    serviceAccountName: default
    secretName: nango-secret

server:
  name: server
  useLoadBalancer: true
  MAILGUN_API_KEY: ""
  replicas: 1

jobs:
  name: jobs
  replicas: 1
  volume:
    name: flows-volume
    claimName: flow-claim
    aws: false
    gcp: false

runner:
  name: runner
  url: http://nango-runner
  replicas: 1

persist:
  name: persist
  url: http://nango-persist
  replicas: 1

shared:
  namespace: default
  encryptionEnabled: false
  flows_path: /flows
  useVolumeForFlows: true
  ENV: production
  DB_HOST: nango-postgresql
  DB_USER: postgres
  DB_PORT: "5432"
  DB_NAME: nango
  DB_SSL: false
  APP_URL: https://your-hosted-instance.com
  CALLBACK_URL: https://your-hosted-instance.com/oauth/callback

temporalio:
  volumeName: nango-temporal-secrets
  TEMPORAL_ADDRESS: nango-sync.abc
  TEMPORAL_NAMESPACE: nango-sync.def

