global:
  #Global namespace values
  namespace: nango
  #Global ontainer image values
  image:
    registry: "nangohq"
    repository: "nango"
    tag: "latest"
    pullPolicy: "Always"
  
security:
  encryptionEnabled: false

logging:
  logsEnabled: true
  logsESUrl: "https://nango-elasticsearch.nango:9200"
  logsESUser: "elastic"
  logsESPassword: "nango"
  logsESIndex: "nango-logs"

auth:
  workos:
    apiKey: ""
    clientId: ""
  nango:
    dashboardUsername: ""
    dashboardPassword: ""
    localNangoUserId: ""

database:
  useSsl: true
  host: "nango-postgresql.nango"
  port: "5432"
  user: "postgres"
  password: "nango123"
  database: "nango"

schedules:
  exportUsageMinutes: "5"
  timeoutLogsMinutes: "10"
  deleteOldJobsLimit: "1000"
  deleteOldDataEveryMinute: "10"
  deleteOldJobsMaxDays: "31"
  deleteOldPivateKeysMaxDays: "31"
  deleteOldOAuthSessionsMaxDays: "2"
  deleteOldInvitationsMaxDays: "2"
  deleteOldConfigsMaxDays: "31"
  deleteOldSyncConfigsMaxDays: "31"
  deleteOldConnectionsMaxDays: "31"
  deleteOldEnvironmentsMaxDays: "31"
  refreshConnectionsEveryMinutes: "10"
  refreshConnectionsLimit: "100"
  persistAccountUsageMinutes: "30"

#Server values
server:
  name: nango-server-dev
  url: http://nango-server-dev.nango
  publicUrl: https://nango-server-dev.dev
  port: "8080"
  webSocketsPath: '/'
  defaultRateLimitPerMinute: 3500
  database:
    useSsl: true

connect:
  publicUrl: https://nango-connect-dev.dev
  port: "3009"

persist:
  name: nango-persist-dev
  url: http://nango-persist-dev.nango
  port: "3007"

orchestrator:
  name: nango-orchestrator-dev
  url: http://nango-orchestrator-dev.nango
  port: "3008"
  database:
    useSsl: true

scheduler:
  expiringTickIntervalMs: "1000"
  cleaningTickIntervalMs: "1000"
  cleaningOlderThanDays: "5"
  schdedulingTickIntervalMs: "100"

jobs:
  name: nango-jobs-dev
  url: http://nango-jobs-dev.nango
  port: "3005"
  providers:
    url: http://nango-server-dev.nango/providers.yaml
    reloadInterval: "60000"
  database:
    useSsl: true
  #TODO: need to structure the properties below slightly differently
  serviceAccount:
    create: true
    name: nango-jobs-dev-sa
  # clusterAdmin: false -> this should be handled by the above
  volume:
    name: flows-volume
    claimName: flow-claim
    storageClassName: standard
    aws: false
    gcp: false

runner:
  name: nango-runner-dev
  url: http://nango-runner-dev.nango
  port: "3006"
  idleMaxDurationMs: "0" 
  memoryWarningThreshold: "85"
  local:
    path: "../runner/dist/app.js"
    nodeId: "1"
  kubernetes:
    namespace: nango-runner
    namespacePerRunner: true
  
postgresql:
  namespace: nango
  enabled: true
  primary:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1000m"
        memory: "2048Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
  auth:
    postgresPassword: nango
    database: nango

elasticsearch:
  namespace: nango
  enabled: true
  clusterName: elastic
  # single node cluster
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  security:
    enabled: true
    elasticPassword: nango