apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.orchestrator.name | default "nango-orchestrator" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3008
  selector:
    app: {{ .Values.orchestrator.name | default "nango-orchestrator" }}
