apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.runner.name | default "nango-runner" }}
spec:
  replicas: {{ .Values.runner.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.runner.name | default "nango-runner" }} 
  template:
    metadata:
      labels:
        app: {{ .Values.runner.name | default "nango-runner" }}
    spec:
      containers:
        - name: {{ .Values.runner.name | default "nango-runner" }}
          image: nangohq/nango-runner:production
          imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
          env:
            - name: NANGO_DB_HOST
              value: {{ .Values.shared.DB_HOST }}
            - name: NANGO_DB_NAME
              value: {{ .Values.shared.DB_NAME | default "" }}
            - name: NANGO_DB_USER
              value: {{ .Values.shared.DB_USER }}
            - name: NANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nango-postgresql
                  key: postgres-password
            - name: NANGO_DB_PORT
              value: "{{ .Values.shared.DB_PORT | default 5432 }}"
            - name: NANGO_DB_SSL
              value: "{{ .Values.shared.DB_SSL | default false }}"
            - name: NANGO_ENCRYPTION_KEY
              value: {{ .Values.shared.ENCRYPTION_KEY | default "" }}
