apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.runner.name | default "nango-runner" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3006
  selector:
    app: {{ .Values.runner.name | default "nango-runner" }}

