apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.runner.name | default "nango-runner" }}
spec:
  replicas: {{ .Values.runner.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.runner.name | default "nango-runner" }} 
  template:
    metadata:
      labels:
        app: {{ .Values.runner.name | default "nango-runner" }}
    spec:
      containers:
        - name: {{ .Values.runner.name | default "nango-runner" }}
          image: nangohq/nango-runner:enterprise
          imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
          env:
            - name: PERSIST_SERVICE_URL
              value: {{ .Values.persist.url }}
            - name: NANGO_ENTERPRISE
              value: "true"
            - name: NANGO_RUNNER_PATH
              value: "/nango/packages/runner/dist/app.js"
