apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.runner.name | default "nango-runner" }}
spec:
  replicas: {{ .Values.runner.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.runner.name | default "nango-runner" }} 
  template:
    metadata:
      labels:
        app: {{ .Values.runner.name | default "nango-runner" }}
    spec:
      {{- with .Values.shared.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.runner.name | default "nango-runner" }}
          image: {{ .Values.shared.imageRegistry | default "nangohq" }}/{{ .Values.shared.imageRepository | default "nango" }}:{{ .Values.runner.tag | default .Values.shared.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
          args: ["node", "packages/runner/dist/app.js"]
          env:
            - name: PERSIST_SERVICE_URL
              value: {{ .Values.persist.url }}
            - name: NANGO_ENTERPRISE
              value: "true"
