apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.shared.namespace }}
  name: {{ .Values.server.name | default "nango-persist" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3007
  selector:
    app: {{ .Values.server.name | default "nango-persist" }}
